apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-04-16T07:29:30Z"
  labels:
    app: anagram
  name: anagram-deployment
  namespace: default
spec:
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 5000
  selector:
    app: anagram
  type: NodePort
