apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-04-16T07:29:30Z"
  labels:
    app: anagram
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:ports:
          .: {}
          k:{"port":5000,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl
    operation: Update
    time: "2020-04-16T07:29:30Z"
  name: anagram-deployment
  namespace: default
  resourceVersion: "22843"
  selfLink: /api/v1/namespaces/default/services/anagram-deployment
  uid: ec8bf05e-2a6a-4f2a-94f1-92ca86287d2f
spec:
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 5000
  selector:
    app: anagram
  sessionAffinity: None
  type: NodePort
